"""Workspace Architect: Automating project documentation and dependency mapping."""

import os
from pathlib import Path
from typing import Dict, List, Any, Optional
from loguru import logger
import datetime

class WorkspaceArchitect:
    """
    Orchestrates the creation and maintenance of architectural documentation
    within the dedicated agent workspace.
    """

    def __init__(self, workspace: Path, fortress_engine: Any, identity: Any):
        self.workspace = workspace
        self.fortress = fortress_engine
        self.identity = identity
        self.dep_map_path = self.workspace / "WORKSPACE_DEPENDENCIES.md"
        logger.info("Workspace Architect initialized.")

    def generate_project_summary(self, activity_id: str, task_description: str, result: str) -> Optional[Path]:
        """Generate detailed individual markdown files for a project or task execution."""
        try:
            project_dir = self.workspace / f"activity_{activity_id}"
            os.makedirs(project_dir, exist_ok=True)
            
            # Content definitions for granular files
            docs = {
                "PURPOSE.md": f"# Purpose\n\n{task_description}",
                "FUNCTIONALITIES.md": f"# Functionalities\n\n{result[:1000]}...",
                "WORKING.md": f"# Working\n\nExecuted within the [{self._detect_dimension(task_description)}] context. Full trace available in system logs.",
                "ARCHITECTURE.md": "# Architecture\n\n- **Deterministic Core**: Fortress Engine, Identity Encyclopedia\n- **Neural Layer**: Strategic Agentic Reasoning",
                "SYSTEM_DESIGN.md": "# System Design\n\nDistributed Swarm Architecture with LMDB-backed state persistence and asynchronous bus communication.",
                "PRACTICAL_ASPECTS.md": "# Practical Aspects\n\n- Resource Auditing enabled.\n- Contextual grounding via ActivityTracker.\n- Automated documentation via WorkspaceArchitect.",
                "FUTURE_IMPROVEMENTS.md": "# Future Improvements\n\n- Deeper semantic analysis of task outcomes.\n- Automated regression testing based on detected dependencies.\n- Dynamic project correlation refinement.",
                "USER_CRITIQUE.md": "# User / Critique Opinions\n\n*[Awaiting human critique or automated introspection results]*"
            }
            
            # Write individual files
            for filename, content in docs.items():
                with open(project_dir / filename, "w", encoding="utf-8") as f:
                    f.write(content + "\n\n---\n*Generated by Antigravity Workspace Architect*")
            
            # Create INDEX.md (Table of Contents)
            index_content = f"# Project Index: {activity_id}\n\n"
            index_content += f"**Task**: {task_description}\n"
            index_content += f"**Date**: {datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n\n"
            index_content += "## Documentation Fragments\n"
            for filename in docs.keys():
                index_content += f"- [{filename.replace('.md', '')}]({filename})\n"
                
            index_path = project_dir / "INDEX.md"
            with open(index_path, "w", encoding="utf-8") as f:
                f.write(index_content + "\n\n---\n*Generated by Antigravity Workspace Architect*")
            
            logger.info(f"Generated granular documentation in {project_dir}")
            return index_path
        except Exception as e:
            logger.error(f"Failed to generate project documentation: {e}")
            return None

    def update_dependency_map(self):
        """Regenerate the global WORKSPACE_DEPENDENCIES.md file."""
        try:
            deps = self.fortress.dependencies.get_all_dependencies()
            correlations = self.identity.get_component_correlations()
            
            content = "# 🕸️ Workspace Dependency & Correlation Map\n\n"
            
            content += "## 📌 Component Correlations\n"
            if correlations:
                for comp in correlations:
                    content += f"- **{comp['name']}**: {comp['responsibility']} (Status: {comp['status']})\n"
            else:
                content += "No active correlations recorded yet.\n"
                
            content += "\n## 🔗 Direct Dependencies\n"
            if deps:
                for dep in deps:
                    content += f"- `{dep['source']}` → `{dep['target']}` ({dep['type']})\n"
            else:
                content += "No cross-module dependencies registered.\n"
                
            content += f"\n\n---\n*Last Updated: {datetime.datetime.now().isoformat()}*"
            
            with open(self.dep_map_path, "w", encoding="utf-8") as f:
                f.write(content)
                
            logger.info("Updated global dependency map.")
        except Exception as e:
            logger.error(f"Failed to update dependency map: {e}")

    def _detect_dimension(self, desc: str) -> str:
        desc = desc.lower()
        if any(kw in desc for kw in ["code", "refactor", "build"]): return "Coding & System Design"
        if any(kw in desc for kw in ["research", "search", "insights"]): return "Real-World Operations"
        return "General Reasoning"
